spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/educationSystem-four
      username: root
      password: caoxing2003
      driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 12345